public class TestClass4
{
    public static void main(final String[] array) {
        double start = System.nanoTime();
        final Account account = new Account(0, "sibelgulmez", "12.01.1885", "London");
        final Account account2 = new Account(1, "gokhankaya", "18.06.1994", "Paris");
        final Account account3 = new Account(2, "gizemsungu", "27.12.1980", "Istanbul");
        final Account account4 = new Account(3, "account1", "1.1.2001", "Kocaeli");
        final Account account5 = new Account(4, "account2", "1.1.2001", "\u0130zmir");
        final Account account6 = new Account(5, "account3", "1.1.2001", "Bursa");
        final Account account7 = new Account(6, "account4", "1.1.2001", "Adana");
        final Account account8 = new Account(7, "account5", "1.1.2001", "Trabzon");
        final Account account9 = new Account(8, "account6", "1.1.2001", "Ankara");
        final Account account10 = new Account(9, "account7", "1.1.2001", "Antalya");
        account.login();
        account.addPost(new Post(1, 0, "", "", "I like JAVA"));
        account.addPost(new Post(2, 0, "", "", "Java The Coffe"));
        account.follow(account3);
        account.follow(account2);
        account.logout();
        account2.login();
        account2.view(account);
        account2.viewPosts(account);
        account2.liking(account, new Like(0, 1, 1));
        account2.make_comment(account, new Comment(1, 1, 1, "me too!"));
        account2.follow(account);
        account2.follow(account3);
        account2.addOut(account3, new Message(1, 1, 2, "This homework is too easy!"));
        account2.logout();
        account3.login();
        account3.check_outbox();
        account3.check_inbox();
        account3.view(account);
        account3.viewPosts(account);
        account3.viewInteraction(account);
        account3.logout();
        account4.login();
        account4.liking(account, new Like(1, 3, 1));
        account4.logout();
        account5.login();
        final Like like = new Like(1, 4, 1);
        account5.liking(account, like);
        account5.viewInteraction(account);
        account5.disliking(account, like);
        account5.viewInteraction(account);
        account5.logout();
        account6.login();
        account6.follow(account);
        account6.logout();
        account7.login();
        account7.follow(account);
        account7.view(account);
        account7.unfollow(account);
        account7.view(account);
        account7.logout();
        account8.login();
        account8.make_comment(account, new Comment(1, 7, 1, "C is better!"));
        account8.logout();
        account9.login();
        final Comment comment = new Comment(1, 8, 1, "ChatGPT is the greatest!");
        account9.make_comment(account, comment);
        account9.viewInteraction(account);
        account9.make_uncomment(account, comment);
        account9.viewInteraction(account);
        account9.logout();
        account10.login();
        account10.view(account);
        System.out.println("-------------*-----------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        account10.follow(account);
        account10.view(account);
        account10.logout();
        account.login();
        account.BlockIt(account10);
        account.view(account);
        account.showHistory();
        account.logout();
        double end = System.nanoTime();
        System.out.println((end-start)/1000000000+ "second is the run time!!");
    }
}